// Application copy lives here. Shared components never decide these texts.
export const content = {
  brand: { name: "Habitar", description: "Tu comunidad, en un lugar", mark: "h.", href: "/" },
  shell: {
    navigation: "Mi comunidad",
    menu: "Abrir navegación",
    skip: "Saltar al contenido",
    footer: "Un espacio para todos",
  },
  home: {
    eyebrow: "TU ESPACIO, TU COMUNIDAD",
    title: "Qué bueno tenerte aquí.",
    description:
      "Todo lo que necesitas para estar al día y disfrutar de tu unidad, en un mismo lugar.",
    sectionTitle: "¿Qué quieres hacer hoy?",
    sectionDescription: "Accede a los servicios de tu comunidad.",
  },
  note: {
    title: "Una comunidad más conectada",
    description:
      "Consulta las novedades de tu unidad y encuentra tus servicios desde este espacio.",
  },
  footer: { left: "Habitar · Hecho para vivir en comunidad", right: "Tu unidad, más cerca." },
  auth: {
    eyebrow: "BIENVENIDO A TU COMUNIDAD",
    headline: "Tu hogar va más allá de tu puerta.",
    description:
      "Un lugar para mantenerte al día, gestionar tus espacios y estar más cerca de tu comunidad.",
    title: "Bienvenido de nuevo",
    subtitle: "Ingresa tus datos para acceder a tu unidad.",
    footer: "Espacios compartidos. Una vida más simple.",
    unavailable: "La conexión de acceso todavía no está configurada.",
    failed: "No se pudo iniciar sesión. Intenta nuevamente.",
    invalid: "El correo o la contraseña no son correctos.",
    logout: "Cerrar sesión",
    loggingOut: "Saliendo…",
    logoutError: "No se pudo cerrar la sesión. Intenta nuevamente.",
    loading: "Cargando tu espacio…",
    loginLink: "Ir al login",
  },
  loginLabels: {
    email: "Correo electrónico",
    password: "Contraseña",
    showPassword: "Mostrar",
    hidePassword: "Ocultar",
    submit: "Iniciar sesión",
    pending: "Ingresando…",
  },
  profile: {
    eyebrow: "TU CUENTA",
    title: "Mi perfil",
    description: "Mantén tu información personal actualizada.",
    formTitle: "Información personal",
    summaryTitle: "Tu información de contacto",
    summaryDescription: "Estos datos permiten mantener la comunicación contigo.",
    saved: "Tus cambios se guardaron correctamente.",
    failed: "No se pudo guardar el perfil. Intenta nuevamente.",
    invalid: "Revisa el nombre y el teléfono antes de guardar.",
    link: "Editar perfil",
    caption: "Mi cuenta",
  },
  profileLabels: {
    name: "Nombre completo",
    nameHelp: "El nombre no se puede modificar desde este formulario.",
    email: "Correo electrónico",
    emailHelp: "El correo de acceso no se puede modificar desde este formulario.",
    phone: "Teléfono",
    phoneHelp: "Debe tener 10 dígitos, por ejemplo 3126222069.",
    submit: "Guardar cambios",
    pending: "Guardando…",
    reset: "Deshacer cambios",
  },
  module: {
    eyebrow: "SERVICIOS DE TU COMUNIDAD",
    title: "Este espacio está por llegar",
    description: "Pronto encontrarás aquí el contenido de este servicio.",
    back: "Volver al inicio",
  },
  preview: {
    label: "Ejemplos de configuración",
    first: "Tres módulos",
    second: "Cuatro módulos",
    user: "Andrea Martínez",
    caption: "Vista de ejemplo",
    title: "Vista previa de la base",
    name: "Patio",
    description: "Conectados en comunidad",
  },
  error: {
    title: "No pudimos cargar esta página",
    description: "Intenta nuevamente para continuar.",
    retry: "Volver a intentar",
    notFound: "Esta página no existe",
    notFoundDescription: "El enlace puede haber cambiado. Puedes volver al inicio.",
  },
};
